### ISSUE TITLE
[Doc]: Fix instructions for OIDC TAI setup

### ISSUE THREAD

**Issue by barbj** [HCL-TECH-SOFTWARE/digital-experience#117]
### Contact Details

Update the issue

### Page(s) impacted

https://opensource.hcltechsw.com/digital-experience/CF217/deployment/manage/security/people/authentication/oidc/dx-update-webshpere-for-oidc/?h=installing+tai#installing-the-oidc-rp-tai

### What is the issue?

- The case of `IfPresent` is wrong,  It is supposed to be `ifPresent`
- Note that the very first step of the [latest rev of the TAIs setup](https://www.ibm.com/docs/en/was-nd/9.0.5?topic=users-configuring-openid-connect-relying-party) says to install the latest version of the TAI.
  - If you can do this, do it.  You cannot imagine how many problems this solves.
- Don't tell them to set `provider_1.callbackServletContext`.  The value you have chosen, `/oidcclient` is the default.  
- Again, `provider_1.useDefaultIdentifierFirst=false` is the default.  Take it out
- `provider_1.mapIdentityToRegistryUser=true` 
  - Isn't that an admin choice and dependent on their OPs?
  - Or is this where the transient user stuff comes into play, so asserted users act as if they're in the registry?
- Regarding this property:
  - `provider_1.signatureAlgorithm=RS256` 
  - The current preferred method is for the TAI to pick up the setting from the token and not hardcode the value.  The OP chooses the signature algorithm and the RP follows.  If you hardcode it here and the OP chooses to up security, then you'll have to modify all the RPs.  If you don't set the value, we'll follow the server.  
  - However, being able to not set this property requires [PH47272](https://www.ibm.com/support/pages/apar/PH47272) in 85523 and 90513 (or OIDC 1.4.0 I think?).  If you instruct to install the latest TAI, then its cool. 
  - You can not set the value at all, or set it to preferred value, `HEADER`.  That puts `HS256` in the `signatureDenyList` and allows everything else that jose4j supports.
- Remove this: 
  - `provider_1.excludedPathFilter=/ibm/console,/ibm/console.*` 
  - It is not a subset of the `interceptedPathFilter`, so the setting is completely unnecessary
- You need to check on this setting.  It appears highly suspect:
  - `provider_1.signVerifyAlias=hcl-dx-oidc-cert`
  - Down in **Adding the hostname or server certificate to the WAS trust store**,  `hcl-dx-oidc-cert` is imported to the trust store as an SSL cert for connecting to the token endpoint, not for verifying JWTs.  We should be verifying JWTs with the keys that are in the JWK that we discover on the discovery endpoint.  What are you going to do if the server rotates keys?
- You don't have to do **Adding the trusted authentication realm** and **Security role to user or group mapping** if you set `useRealm` to `WAS_DEFAULT`.
  > This property and value designates your user and groups from your idToken or JWT to the WebSphere realm instead of the OP's external realm. When you use this setting, you are not required to add the OP's realm as an external trusted realm or map the trusted realms to your applications.
 

### Version

None

**Comment by biancaluna** [comment]
Instructions are now updated: https://opensource.hcltechsw.com/digital-experience/latest/deployment/manage/security/people/authentication/oidc/dx-update-webshpere-for-oidc/
