### ISSUE TITLE
[Doc]: Invalid cpu.limit value for the persistenceNode pod?

### ISSUE THREAD

**Issue by hhue13** [HCL-TECH-SOFTWARE/digital-experience#160]
### Contact Details

h.hueble@alpium-it.com

### Page(s) impacted

https://opensource.hcltechsw.com/digital-experience/CF222/guide_me/performance_tuning/kubernetes/rendering_medium_config.html

### What is the issue?

![limits](https://github.com/user-attachments/assets/c3701a34-a969-4ac7-960d-c4bd7dc931ee)

As far as I know the cpu.requested (1200) can not be higher than cpu.limit(1000). Please can you verify these numbers again?

Thanks, Hermann

### Version

None

**Comment by biancaluna** [comment]
Hi @hhue13 , the page has been updated: https://opensource.hcltechsw.com/digital-experience/latest/guide_me/performance_tuning/kubernetes/rendering_medium_config/ Thanks!
