### ISSUE TITLE
Add Javadoc links to documenation (for developers consumption)

### ISSUE THREAD

**Issue by DanieleVistalli** [HCL-TECH-SOFTWARE/digital-experience#19]
HCL DX Api documentation includes:

- API Javadoc (DX and WCM)
- SPI Javadoc (DX and WCM)
- Javascript documentation (for theme modules)
- Swagger documentation for new APIs (Ring API)

All this should be available online as a site that's part of documentationa and integrated into the build pipeline.

Having it as part of official HCL Documentation would make it indexed by search engines and make developer's life a lot easier.

**Comment by sunilkn020** [comment]
We are working with the dev team and we will add them in coming releases.

**Comment by davidsayer57** [comment]
Looking to add in cf-212

**Comment by AshfaqMemon** [comment]
Is this completed? If yes, can you please provide me with the link of JavaDoc?

**Comment by ThomasHurek** [comment]
You can find links here: https://opensource.hcltechsw.com/digital-experience/CF214/extend_dx/development_tools/reference_docs/reference_docs/?h=reference+doc

**Comment by sunilkn020** [comment]
Hi @AshfaqMemon, 

As we have provided you with link to doc, we are going ahead and closing this issue. If any query you can create a new issue.

Thanks,
Sunil
