### ISSUE TITLE
[Doc]: Download and deploy through HCL Harbor repository

### ISSUE THREAD

**Issue by hhue13** [HCL-TECH-SOFTWARE/digital-experience#26]
### Contact Details

hhue13@gmail.com

### Page(s) impacted

https://opensource.hcltechsw.com/digital-experience/cf205/platform/software_download/dx_from_harbor/

### What is the issue?

The link to [Re-tagging images](https://opensource.hcltechsw.com/digital-experience/cf205/platform/software_download/platform/kubernetes/deployment/preparation/prepare_load_images.md#re-tag-images) dies not work and gives a 404 error!

### Version

Kubernetes deployment - Helm charts

**Comment by sunilkn020** [comment]
The link is fixed in the CF208 release.
