### ISSUE TITLE
Broken Links on the "Containerization requirements and limitations" page

### ISSUE THREAD

**Issue by Giancarlo-Giannini** [HCL-TECH-SOFTWARE/digital-experience#31]
There are a list of broken links on the "Containerization requirements and limitations" page:

- **Operator-based deployments**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/limitations_requirements/deploy_container_platforms.md 
- **Helm-based deployments**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/limitations_requirements/helm.md
- **Migrating from Operator-based to Helm-based deployments**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/limitations_requirements/helm_operator_migration.md
- **Configuring PVCs in a Helm deployment**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/limitations_requirements/helm_persistent_volume_claims.md#configuration_parameters
- **Customizing the container for Operator-based deployments**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/limitations_requirements/customizing_container_deployment.md#section_a2l_xhv_4nb
- **Migrating from Operator-based to Helm-based deployments**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/limitations_requirements/helm_operator_migration.md
- **HCL Digital Experience 9.5 Roadmap**: Container deployment: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/install/rm_container_deployment.md
- **DX Kubernetes support matrix**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/containerization/c_kubesupportstatement.md
- **Deploy DX 9.5 Container to Red Hat OpenShift**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/containerization/openshift.md
- **Deploy DX Container to Amazon EKS**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/containerization/kubernetes_eks.md
- **Deploy DX CF192 and later release Containers to Amazon EKS**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/containerization/kubernetes_eks_cf192andlater.md
- **Deploy DX CF191 and earlier release Containers to Amazon EKS**: https://opensource.hcltechsw.com/digital-experience/cf206/get_started/plan_deployment/container_deployment/containerization/kubernetes_eks_cf191andearlier.md

**Comment by sunilkn020** [comment]
Broken links are fixed in the CF208 release.
